### ISSUE TITLE
the triggers you have used

### ISSUE THREAD

**Issue by aborruso** [simonw/coronavirus-data-gov-archive#4]
Hi Simon,
in your yml workflow you have

```
on:
  push:
  repository_dispatch:
  schedule:
```

A question: why did you have insert also push?

Thank you, very useful your post about this task!!
